# Generated by Django 3.1.5 on 2021-01-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(blank=True, null=True, verbose_name='リリース日')),
                ('initial', models.IntegerField(verbose_name='初期総合値')),
                ('maximum', models.IntegerField(verbose_name='最大総合値')),
                ('level', models.IntegerField(verbose_name='最大レベル')),
                ('player_style', models.CharField(max_length=10, verbose_name='選手タイプ')),
                ('rarity', models.CharField(max_length=10, verbose_name='レアリティ')),
                ('player_name', models.CharField(max_length=50, verbose_name='選手名')),
                ('country', models.CharField(max_length=30, verbose_name='国名')),
                ('league', models.CharField(max_length=30, verbose_name='所属リーグ')),
                ('club', models.CharField(max_length=30, verbose_name='所属クラブ')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('height', models.IntegerField(verbose_name='身長')),
                ('body_weight', models.IntegerField(verbose_name='体重')),
                ('dominant_foot', models.CharField(max_length=2, verbose_name='利き足')),
                ('position', models.CharField(max_length=4, verbose_name='ポジション')),
                ('playstyle', models.CharField(max_length=30, verbose_name='プレースタイル')),
                ('player_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_skill', models.CharField(blank=True, max_length=20, verbose_name='スキル入力')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pespost.player')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation_images', models.ImageField(upload_to='')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pespost.player')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_sense', models.IntegerField(verbose_name='OFセンス')),
                ('ball_control', models.IntegerField(verbose_name='ボールコントロール')),
                ('dribble', models.IntegerField(verbose_name='ドリブル')),
                ('ball_keep', models.IntegerField(verbose_name='ボールキープ')),
                ('grander_pass', models.IntegerField(verbose_name='グランダーパス')),
                ('fly_pass', models.IntegerField(verbose_name='フライパス')),
                ('determining_power', models.IntegerField(verbose_name='決定力')),
                ('heading', models.IntegerField(verbose_name='ヘディング')),
                ('place_kick', models.IntegerField(verbose_name='プレースキック')),
                ('curve', models.IntegerField(verbose_name='カーブ')),
                ('speed', models.IntegerField(verbose_name='スピード')),
                ('instantaneous_power', models.IntegerField(verbose_name='瞬発力')),
                ('kick_power', models.IntegerField(verbose_name='キック力')),
                ('jumping', models.IntegerField(verbose_name='ジャンプ')),
                ('physical_contact', models.IntegerField(verbose_name='フィジカルコンタクト')),
                ('body_control', models.IntegerField(verbose_name='ボディコントロール')),
                ('physical_fitness', models.IntegerField(verbose_name='体力')),
                ('defense_sense', models.IntegerField(verbose_name='ディフェンスセンス')),
                ('take_the_ball', models.IntegerField(verbose_name='ボール奪取')),
                ('aggressiveness', models.IntegerField(verbose_name='アグレッシブネス')),
                ('gksense', models.IntegerField(verbose_name='GKセンス')),
                ('catching', models.IntegerField(verbose_name='キャッチング')),
                ('clearing', models.IntegerField(verbose_name='クリアリング')),
                ('cobraging', models.IntegerField(verbose_name='コブラシング')),
                ('deflectiveing', models.IntegerField(verbose_name='ディフレクティング')),
                ('reverse_foot_frequency', models.IntegerField(verbose_name='逆足頻度')),
                ('reverse_foot_accuracy', models.IntegerField(verbose_name='逆足精度')),
                ('condition_stability', models.IntegerField(verbose_name='コンディション安定度')),
                ('injury_resistance', models.IntegerField(verbose_name='ケガ耐性')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pespost.player')),
            ],
        ),
    ]
